### PR TITLE
Port to polymer 0.9

### PR DESCRIPTION
**Pull request by liuwenchao**
For #24

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @liuwenchao,

I took the opportunity to update this to polymer v0.9. Could you rebase and justify your changes? Remember that this template should be compliant with webcomponents/xtag-boilerplate and webcomponents/element-boilerplate, which are all used in webcomponents/generator-element.

**Comment by liuwenchao** [comment]
Well, to make it compliant with webcomponents/xtag-boilerplate and webcomponents/element-boilerplate, it seems to all boil down to one line change. 

I think we probably should add `properties` into my-element.html, but not seeing it's declared in xtag or element repositories.

**Comment by zenorocha** [comment]
Great, thanks @liuwenchao!

**Comment by zenorocha** [comment]
I agree with you. We should add `properties` to Polymer and similar approaches for x-tag and vanilla boilerplate too. Could you send a PR?

**Pull request merged**
